// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqFiL0jWXYLhi6Na_3f8WQ9Bn_IpYhfT8',
    appId: '1:566969417122:web:86540976bdde1746da06fb',
    messagingSenderId: '566969417122',
    projectId: 'random-project-concept',
    authDomain: 'random-project-concept.firebaseapp.com',
    storageBucket: 'random-project-concept.appspot.com',
    measurementId: 'G-9G6Q9G6YQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVZ6okVse-QudQK4cOJ87CcF1cI4i49K0',
    appId: '1:566969417122:android:38927941bad4e9ffda06fb',
    messagingSenderId: '566969417122',
    projectId: 'random-project-concept',
    storageBucket: 'random-project-concept.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvQspYxS9Mt9I1NkqPEQmpf87mf3BFoRM',
    appId: '1:566969417122:ios:7f079624c1c86c06da06fb',
    messagingSenderId: '566969417122',
    projectId: 'random-project-concept',
    storageBucket: 'random-project-concept.appspot.com',
    iosBundleId: 'com.mrzg.rcp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvQspYxS9Mt9I1NkqPEQmpf87mf3BFoRM',
    appId: '1:566969417122:ios:922acdf52e049734da06fb',
    messagingSenderId: '566969417122',
    projectId: 'random-project-concept',
    storageBucket: 'random-project-concept.appspot.com',
    iosBundleId: 'com.example.bnf.RunnerTests',
  );
}
