// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAImsqQJM-fB8aPtAanFuj2W9zbxIO0ueM',
    appId: '1:756385223651:web:a24422b2d45572b2a606d6',
    messagingSenderId: '756385223651',
    projectId: 'random-concept-projects',
    authDomain: 'random-concept-projects.firebaseapp.com',
    storageBucket: 'random-concept-projects.appspot.com',
    measurementId: 'G-NF4LN07Q9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7nEpVEWe6hYUnjdcXmL7QjrOU-ZbcC4I',
    appId: '1:756385223651:android:544077dc19baf7fea606d6',
    messagingSenderId: '756385223651',
    projectId: 'random-concept-projects',
    storageBucket: 'random-concept-projects.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6ESciKjVN673qdv7usDf8UvkpGnZ3g5Q',
    appId: '1:756385223651:ios:f432da6a7157d638a606d6',
    messagingSenderId: '756385223651',
    projectId: 'random-concept-projects',
    storageBucket: 'random-concept-projects.appspot.com',
    iosBundleId: 'com.mrzg.rcp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6ESciKjVN673qdv7usDf8UvkpGnZ3g5Q',
    appId: '1:756385223651:ios:7d225f7536480a7ea606d6',
    messagingSenderId: '756385223651',
    projectId: 'random-concept-projects',
    storageBucket: 'random-concept-projects.appspot.com',
    iosBundleId: 'com.mrzg.rcp.RunnerTests',
  );
}
